---
id: rurema
tags:
  - rurema
version: 1.0.0
licenses:
  - GPLv3+
  - CC BY-SA 3.0
author:
  markup_language: rd
  name: okkez
  email: okkez000@gmail.com
  rubygems_user: okkez
  slideshare_user: okkez
  speaker_deck_user:
